# Default settings for building the UB CS Education Handbook
# See: https://pandoc.org/MANUAL.html#default-files
#
# This is a base file. Use html.yaml or pdf.yaml.

from: markdown
input-files: 
  - source/introduction.md
  - source/vision_and_goals.md
  - source/tracks/tracks.md
  - source/tracks/ub_teach_track.md
  - source/tracks/initial_certificate_track.md
  - source/tracks/professional_certificate_track.md
  - source/tracks/initial_professional_certificate_track.md
  - source/tracks/advanced_certificate_track_for_in_service_teachers.md
  - source/courses/courses.md
  - source/courses/lai_508.md
  - source/courses/lai_595.md
  - source/courses/lai_605.md
  - source/courses/lai_611.md
  - source/courses/lai_667.md
  - source/courses/lai_668.md
  - source/courses/lai_674.md
  - source/courses/lai_676.md
  - source/courses/lai_677.md
  - source/courses/lai_686.md
  - source/courses/lai_700.md
  - source/courses/dee_520.md
  - source/appendices/changelog.md
  - source/appendices/csta_standards.md
  - source/appendices/field_experiences.md
  - source/appendices/resources.md

table-of-contents: true
standalone: true
number-sections: true
number-offset: [-1,-1,-1,-1,-1]

metadata:
  author: Dr. Chris Proctor
  institution: University at Buffalo, SUNY
  email: chrisp@buffalo.edu
  title: UB Computer Science Education Handbook
  date: "January 25, 2023"
  version: "0.0.8 DRAFT"

citeproc: true
csl: apa-7th-edition
css: handbook.css
bibliography: source/bibliography.bib

filters:
 - pandoc-plot
